### PR TITLE
fix bug in showLinePlots

### PR DESCRIPTION
**Pull request by fbenke-pik**
Fix https://github.com/pik-piam/mip/issues/118

### CODE REVIEW

**Comment by robertpietzcker** [comment]
I think you meant this issue, no? https://github.com/pik-piam/mip/issues/118

**Review by robertpietzcker — APPROVED** [review]
I don't understand the R code, but if it leads to showLinePlots working as before, thanks a lot!

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
:point_right: #120
All of these conditionals can be removed if the default arguments are stated explicitly.

**Comment by fbenke-pik** [comment]
Fine by me. Please go ahead and merge.

**Pull request closed without merging**
