### PR TITLE
Remove Convergence Plot

### PR DESCRIPTION
**Pull request by fbenke-pik**
Removes the REMIND convergence plot, as mip was originally meant as an application independent visualization package.

### CODE REVIEW

**Review by LaviniaBaumstark — COMMENTED** [review]
sorry, a bit late for asking this: are we sure that this funciton should be in the mip-package? As we are using some specific variable names, maybe it should go to `remind2`?

**Comment by fbenke-pik** [comment]
You can argue either way. If you stress the visualization aspect, it goes into mip. If you stress the aspect of coding of GAMS logic and variables in R, it goes into remind2.

**Comment by LaviniaBaumstark** [comment]
Let's keep it here for now

**Comment by tscheypidi** [comment]
mip was originally meant as an application independent visualization package. From that perspective these specific functions violate this definition. But I also have to say that its been a while that I had a look at the package. So there might be already violations in there?

**Comment by orichters** [comment]
I'm sorry, but I don't really know what is going on here and don't have time to dig into it at the moment, so I let you find a good solution…

**Comment by fbenke-pik** [comment]
Deleting mipConvergence and moving it to remind2.

**Pull request merged**
